language: c
addons:
    apt:
        packages:
            - bc
            - binutils-arm-linux-gnueabi
            - build-essential
            - check
            - cmake
            - g++-arm-linux-gnueabi
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
            - libncurses5-dev
            - libncursesw5-dev
            - linux-tools-common
            - qemu
            - tmux
            - unzip
            - valgrind
            - zip
script:
    - make mode=debug
    - make mode=release
    - make target=qemu build
    - make target=qemu mode=debug
    - make target=qemu mode=release

