dist: trusty
sudo: false

language: c
addons:
    apt:
        packages:
            - bc
            - binutils-arm-linux-gnueabi
            - build-essential
            - check
            - cmake
            - g++-arm-linux-gnueabi
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
            - libncurses5-dev
            - libncursesw5-dev
            - linux-tools-common
            - qemu
            - tmux
            - unzip
            - valgrind
            - zip
before_install:
    - pip install --user cpp-coveralls
script:
    - make mode=debug
    - make mode=debug test
    - make mode=release
    - make mode=release test
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
